#!/usr/bin/env python3
"""Regenerate every document that is derived from data.

    python tools/generate.py            # write them
    python tools/generate.py --check    # fail if any is stale (for CI / pre-commit)

Generated:
    docs/rulebook/03-factions.md    from data/factions.yaml
    docs/rulebook/12-keywords.md    from data/keywords.yaml
    docs/design/crews.md            from data/crews.yaml

Never hand-edit those three. Edit the YAML and run this.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import card_io  # noqa: E402
import rules  # noqa: E402

BANNER = "<!-- GENERATED by tools/generate.py — edit the YAML in data/, not this file. -->"


def factions_doc(world: rules.World) -> str:
    out = [BANNER, "", "# 3. The Factions (Lore & Core Identity)", "",
           "Cards belong to one of four colored factions, representing different **methodologies**.",
           "",
           "> **Two-axis identity.** Faction is *how you win*. **Crew** is *who you run with*.",
           "> They are independent — one crew's members can span three factions.", ""]
    for faction in world.factions:
        stale = "" if faction.get("reviewed") else "  ·  ⚠️ *draft, unreviewed*"
        out += ["---", "", f"## {faction.get('emoji','')} {faction['name']}{stale}", "",
                faction.get("identity", "").strip(), "",
                f"> **The printed weakness:** *{faction.get('weakness','').strip()}*", ""]

        unique = faction.get("unique") or {}
        never = faction.get("never") or {}
        out += ["### Toolkit", "", "| | |", "|---|---|"]
        for label, items in (("**Unique to them**", (unique.get("keywords") or []) + (unique.get("effects") or [])),
                             ("**Never**", (never.get("keywords") or []) + (never.get("effects") or []))):
            out.append(f"| {label} | {' · '.join(items) if items else '—'} |")
        out += ["", "*Anything not listed is shared.*", ""]

        out += ["### Where they can answer a plan", "", "| Window | | |", "|---|---|---|"]
        for key in rules.WINDOW_KEYS:
            level = (faction.get("windows") or {}).get(key, "—")
            mark = {"strong": "**STRONG**", "weak": "weak", "blind": "blind"}.get(level, level)
            note = (faction.get("window_notes") or {}).get(key, "")
            out.append(f"| {rules.WINDOW_LABELS[key]} | {mark} | {note} |")
        out.append("")
        if faction.get("notes"):
            out += [f"> {faction['notes'].strip()}", ""]
    return "\n".join(out).rstrip() + "\n"


def keywords_doc(world: rules.World) -> str:
    order = [(f["name"], f.get("emoji", "")) for f in world.factions]
    out = [BANNER, "", "# 12. Factions & Exclusive Keywords (The Roles)", "",
           "Keywords are **Roles** a Character plays. Each is exclusive to its faction; a card",
           "carrying another faction's keyword is a hard error (F2).", "",
           "Point values are the budget cost charged by `tools/scoring.py`.", ""]
    for name, emoji in order:
        rows = [k for k in world.keywords if k["faction"] == name]
        if not rows:
            continue
        out += ["---", "", f"## {emoji} The {name}", "", "| Keyword | Pts | Effect |", "|---|---:|---|"]
        for k in sorted(rows, key=lambda x: (x["points"], x["name"])):
            out.append(f"| **{k['name']}** | {k['points']} | {k['definition']} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def crews_doc(world: rules.World) -> str:
    out = [BANNER, "", "# The Crews", "",
           "A crew is a **plan**. Faction is how you fight; crew is what you're trying to do.",
           "Every card must advance the plan by a *different* road.", ""]
    for crew in world.crews:
        members = [c for c in world.cards if c.meta.get("crew") == crew["name"]]
        factions = sorted({c.faction for c in members if c.faction})
        stale = "" if crew.get("reviewed") else "  ·  ⚠️ *draft, unreviewed*"
        out += ["---", "", f"## {crew['name']}{stale}", "",
                f"**Plan.** {crew.get('plan','—').strip()}", ""]
        if crew.get("lore_basis"):
            out += [f"*Lore basis:* {crew['lore_basis'].strip()}", ""]
        out += [f"**Coordination:** {crew.get('coordination','—')}  ·  "
                f"**Signature:** {crew.get('signature') or '—'}  ·  "
                f"**{len(members)} cards across {len(factions)} factions** "
                f"({', '.join(factions) or 'none'})", ""]
        expressions = {e.get("card"): e for e in (crew.get("expressions") or [])}
        out += ["| Card | Faction | The road it takes |", "|---|---|---|"]
        for card in sorted(members, key=lambda c: c.name):
            entry = expressions.get(card.meta.get("slug")) or {}
            road = entry.get("road") or "_no road declared_"
            out.append(f"| {card.name} | {card.faction} | {road} |")
        out.append("")
        if crew.get("note"):
            out += [f"> {crew['note'].strip()}", ""]
    return "\n".join(out).rstrip() + "\n"


TARGETS = {
    "docs/rulebook/03-factions.md": factions_doc,
    "docs/rulebook/12-keywords.md": keywords_doc,
    "docs/design/crews.md": crews_doc,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if anything is stale")
    args = parser.parse_args()

    world = rules.load_world()
    stale = []
    for relative, builder in TARGETS.items():
        path = card_io.REPO_ROOT / relative
        fresh = builder(world)
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == fresh:
            print(f"  ok      {relative}")
            continue
        if args.check:
            stale.append(relative)
            print(f"  STALE   {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(fresh, encoding="utf-8")
            print(f"  written {relative}")
    if stale:
        print(f"\n{len(stale)} generated file(s) out of date — run: python tools/generate.py")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
